/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef schema_TYPES_H
#define schema_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace surfingdb { namespace table { namespace schema {

struct RowType {
  enum type {
    BOOL = 0,
    INT = 1,
    LONG = 2,
    DOUBLE = 3,
    BINARY = 4,
    STRING = 5,
    LIST = 6,
    MAP = 7
  };
};

extern const std::map<int, const char*> _RowType_VALUES_TO_NAMES;


class Field {
 public:

  static const char* ascii_fingerprint; // = "6E7DD25E88B43484CFC93FCB15DCA1AF";
  static const uint8_t binary_fingerprint[16]; // = {0x6E,0x7D,0xD2,0x5E,0x88,0xB4,0x34,0x84,0xCF,0xC9,0x3F,0xCB,0x15,0xDC,0xA1,0xAF};

  Field() : type((RowType::type)0), len(0) {
  }

  virtual ~Field() throw() {}

  RowType::type type;
  int64_t len;

  void __set_type(const RowType::type val) {
    type = val;
  }

  void __set_len(const int64_t val) {
    len = val;
  }

  bool operator == (const Field & rhs) const
  {
    if (!(type == rhs.type))
      return false;
    if (!(len == rhs.len))
      return false;
    return true;
  }
  bool operator != (const Field &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Field & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Field &a, Field &b);

typedef struct _PValue__isset {
  _PValue__isset() : bool_val(false), byte_val(false), short_val(false), int_val(false), long_val(false), double_val(false), binary_val(false), string_val(false) {}
  bool bool_val;
  bool byte_val;
  bool short_val;
  bool int_val;
  bool long_val;
  bool double_val;
  bool binary_val;
  bool string_val;
} _PValue__isset;

class PValue {
 public:

  static const char* ascii_fingerprint; // = "24B4E64A16E3BBE39C7D7812C6430DB7";
  static const uint8_t binary_fingerprint[16]; // = {0x24,0xB4,0xE6,0x4A,0x16,0xE3,0xBB,0xE3,0x9C,0x7D,0x78,0x12,0xC6,0x43,0x0D,0xB7};

  PValue() : bool_val(0), byte_val(0), short_val(0), int_val(0), long_val(0), double_val(0), binary_val(), string_val() {
  }

  virtual ~PValue() throw() {}

  bool bool_val;
  int8_t byte_val;
  int16_t short_val;
  int32_t int_val;
  int64_t long_val;
  double double_val;
  std::string binary_val;
  std::string string_val;

  _PValue__isset __isset;

  void __set_bool_val(const bool val) {
    bool_val = val;
    __isset.bool_val = true;
  }

  void __set_byte_val(const int8_t val) {
    byte_val = val;
    __isset.byte_val = true;
  }

  void __set_short_val(const int16_t val) {
    short_val = val;
    __isset.short_val = true;
  }

  void __set_int_val(const int32_t val) {
    int_val = val;
    __isset.int_val = true;
  }

  void __set_long_val(const int64_t val) {
    long_val = val;
    __isset.long_val = true;
  }

  void __set_double_val(const double val) {
    double_val = val;
    __isset.double_val = true;
  }

  void __set_binary_val(const std::string& val) {
    binary_val = val;
    __isset.binary_val = true;
  }

  void __set_string_val(const std::string& val) {
    string_val = val;
    __isset.string_val = true;
  }

  bool operator == (const PValue & rhs) const
  {
    if (__isset.bool_val != rhs.__isset.bool_val)
      return false;
    else if (__isset.bool_val && !(bool_val == rhs.bool_val))
      return false;
    if (__isset.byte_val != rhs.__isset.byte_val)
      return false;
    else if (__isset.byte_val && !(byte_val == rhs.byte_val))
      return false;
    if (__isset.short_val != rhs.__isset.short_val)
      return false;
    else if (__isset.short_val && !(short_val == rhs.short_val))
      return false;
    if (__isset.int_val != rhs.__isset.int_val)
      return false;
    else if (__isset.int_val && !(int_val == rhs.int_val))
      return false;
    if (__isset.long_val != rhs.__isset.long_val)
      return false;
    else if (__isset.long_val && !(long_val == rhs.long_val))
      return false;
    if (__isset.double_val != rhs.__isset.double_val)
      return false;
    else if (__isset.double_val && !(double_val == rhs.double_val))
      return false;
    if (__isset.binary_val != rhs.__isset.binary_val)
      return false;
    else if (__isset.binary_val && !(binary_val == rhs.binary_val))
      return false;
    if (__isset.string_val != rhs.__isset.string_val)
      return false;
    else if (__isset.string_val && !(string_val == rhs.string_val))
      return false;
    return true;
  }
  bool operator != (const PValue &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PValue & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(PValue &a, PValue &b);

typedef struct _Value__isset {
  _Value__isset() : p_val(false), list_value(false), map_value(false) {}
  bool p_val;
  bool list_value;
  bool map_value;
} _Value__isset;

class Value {
 public:

  static const char* ascii_fingerprint; // = "0C3E1FA8A21C734546641C1B5D12B2FE";
  static const uint8_t binary_fingerprint[16]; // = {0x0C,0x3E,0x1F,0xA8,0xA2,0x1C,0x73,0x45,0x46,0x64,0x1C,0x1B,0x5D,0x12,0xB2,0xFE};

  Value() {
  }

  virtual ~Value() throw() {}

  PValue p_val;
  std::vector<PValue>  list_value;
  std::map<Field, PValue>  map_value;

  _Value__isset __isset;

  void __set_p_val(const PValue& val) {
    p_val = val;
    __isset.p_val = true;
  }

  void __set_list_value(const std::vector<PValue> & val) {
    list_value = val;
    __isset.list_value = true;
  }

  void __set_map_value(const std::map<Field, PValue> & val) {
    map_value = val;
    __isset.map_value = true;
  }

  bool operator == (const Value & rhs) const
  {
    if (__isset.p_val != rhs.__isset.p_val)
      return false;
    else if (__isset.p_val && !(p_val == rhs.p_val))
      return false;
    if (__isset.list_value != rhs.__isset.list_value)
      return false;
    else if (__isset.list_value && !(list_value == rhs.list_value))
      return false;
    if (__isset.map_value != rhs.__isset.map_value)
      return false;
    else if (__isset.map_value && !(map_value == rhs.map_value))
      return false;
    return true;
  }
  bool operator != (const Value &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Value & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Value &a, Value &b);


class RowSchema {
 public:

  static const char* ascii_fingerprint; // = "EFDB30DD9CF5CAC5B8C25E1D79058D2E";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xDB,0x30,0xDD,0x9C,0xF5,0xCA,0xC5,0xB8,0xC2,0x5E,0x1D,0x79,0x05,0x8D,0x2E};

  RowSchema() {
  }

  virtual ~RowSchema() throw() {}

  std::vector<Field>  fields;
  std::vector<Value>  values;

  void __set_fields(const std::vector<Field> & val) {
    fields = val;
  }

  void __set_values(const std::vector<Value> & val) {
    values = val;
  }

  bool operator == (const RowSchema & rhs) const
  {
    if (!(fields == rhs.fields))
      return false;
    if (!(values == rhs.values))
      return false;
    return true;
  }
  bool operator != (const RowSchema &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RowSchema & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(RowSchema &a, RowSchema &b);

}}} // namespace

#endif
