/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "schema_constants.h"

namespace surfingdb { namespace table { namespace schema {

const schemaConstants g_schema_constants;

schemaConstants::schemaConstants() {
  Type_Size.insert(std::make_pair((RowType::type)1, 1LL));
  Type_Size.insert(std::make_pair((RowType::type)2, 4LL));

}

}}} // namespace

