/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "schema_constants.h"

namespace matcha { namespace meta { namespace schema {

const schemaConstants g_schema_constants;

schemaConstants::schemaConstants() {
}

}}} // namespace

