/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "schema_types.h"

#include <algorithm>

namespace surfingdb { namespace meta { namespace schema {

int _kRowTypeValues[] = {
  RowType::VOID,
  RowType::BOOL,
  RowType::INT,
  RowType::LONG,
  RowType::DOUBLE,
  RowType::STRING,
  RowType::LIST,
  RowType::MAP
};
const char* _kRowTypeNames[] = {
  "VOID",
  "BOOL",
  "INT",
  "LONG",
  "DOUBLE",
  "STRING",
  "LIST",
  "MAP"
};
const std::map<int, const char*> _RowType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(8, _kRowTypeValues, _kRowTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

const char* Field::ascii_fingerprint = "56EDE1E97BD242B68F0241975FE25DEA";
const uint8_t Field::binary_fingerprint[16] = {0x56,0xED,0xE1,0xE9,0x7B,0xD2,0x42,0xB6,0x8F,0x02,0x41,0x97,0x5F,0xE2,0x5D,0xEA};

uint32_t Field::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_name = false;
  bool isset_type = false;
  bool isset_max_unit_size = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          isset_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->type = (RowType::type)ecast0;
          isset_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->max_unit_size);
          isset_max_unit_size = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast1;
          xfer += iprot->readI32(ecast1);
          this->list_type = (RowType::type)ecast1;
          this->__isset.list_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->max_list_unit_size);
          this->__isset.max_list_unit_size = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->map_key_type = (RowType::type)ecast2;
          this->__isset.map_key_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast3;
          xfer += iprot->readI32(ecast3);
          this->map_value_type = (RowType::type)ecast3;
          this->__isset.map_value_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->max_map_key_unit_size);
          this->__isset.max_map_key_unit_size = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->max_map_value_unit_size);
          this->__isset.max_map_value_unit_size = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_max_unit_size)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t Field::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("Field");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32((int32_t)this->type);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("max_unit_size", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->max_unit_size);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.list_type) {
    xfer += oprot->writeFieldBegin("list_type", ::apache::thrift::protocol::T_I32, 4);
    xfer += oprot->writeI32((int32_t)this->list_type);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.max_list_unit_size) {
    xfer += oprot->writeFieldBegin("max_list_unit_size", ::apache::thrift::protocol::T_I64, 5);
    xfer += oprot->writeI64(this->max_list_unit_size);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.map_key_type) {
    xfer += oprot->writeFieldBegin("map_key_type", ::apache::thrift::protocol::T_I32, 6);
    xfer += oprot->writeI32((int32_t)this->map_key_type);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.map_value_type) {
    xfer += oprot->writeFieldBegin("map_value_type", ::apache::thrift::protocol::T_I32, 7);
    xfer += oprot->writeI32((int32_t)this->map_value_type);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.max_map_key_unit_size) {
    xfer += oprot->writeFieldBegin("max_map_key_unit_size", ::apache::thrift::protocol::T_I64, 8);
    xfer += oprot->writeI64(this->max_map_key_unit_size);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.max_map_value_unit_size) {
    xfer += oprot->writeFieldBegin("max_map_value_unit_size", ::apache::thrift::protocol::T_I64, 9);
    xfer += oprot->writeI64(this->max_map_value_unit_size);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Field &a, Field &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.type, b.type);
  swap(a.max_unit_size, b.max_unit_size);
  swap(a.list_type, b.list_type);
  swap(a.max_list_unit_size, b.max_list_unit_size);
  swap(a.map_key_type, b.map_key_type);
  swap(a.map_value_type, b.map_value_type);
  swap(a.max_map_key_unit_size, b.max_map_key_unit_size);
  swap(a.max_map_value_unit_size, b.max_map_value_unit_size);
  swap(a.__isset, b.__isset);
}

const char* PValue::ascii_fingerprint = "24B4E64A16E3BBE39C7D7812C6430DB7";
const uint8_t PValue::binary_fingerprint[16] = {0x24,0xB4,0xE6,0x4A,0x16,0xE3,0xBB,0xE3,0x9C,0x7D,0x78,0x12,0xC6,0x43,0x0D,0xB7};

uint32_t PValue::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->bool_val);
          this->__isset.bool_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BYTE) {
          xfer += iprot->readByte(this->byte_val);
          this->__isset.byte_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->short_val);
          this->__isset.short_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->int_val);
          this->__isset.int_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->long_val);
          this->__isset.long_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->double_val);
          this->__isset.double_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->binary_val);
          this->__isset.binary_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->string_val);
          this->__isset.string_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t PValue::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("PValue");

  if (this->__isset.bool_val) {
    xfer += oprot->writeFieldBegin("bool_val", ::apache::thrift::protocol::T_BOOL, 1);
    xfer += oprot->writeBool(this->bool_val);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.byte_val) {
    xfer += oprot->writeFieldBegin("byte_val", ::apache::thrift::protocol::T_BYTE, 2);
    xfer += oprot->writeByte(this->byte_val);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.short_val) {
    xfer += oprot->writeFieldBegin("short_val", ::apache::thrift::protocol::T_I16, 3);
    xfer += oprot->writeI16(this->short_val);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.int_val) {
    xfer += oprot->writeFieldBegin("int_val", ::apache::thrift::protocol::T_I32, 4);
    xfer += oprot->writeI32(this->int_val);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.long_val) {
    xfer += oprot->writeFieldBegin("long_val", ::apache::thrift::protocol::T_I64, 5);
    xfer += oprot->writeI64(this->long_val);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.double_val) {
    xfer += oprot->writeFieldBegin("double_val", ::apache::thrift::protocol::T_DOUBLE, 6);
    xfer += oprot->writeDouble(this->double_val);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.binary_val) {
    xfer += oprot->writeFieldBegin("binary_val", ::apache::thrift::protocol::T_STRING, 7);
    xfer += oprot->writeBinary(this->binary_val);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.string_val) {
    xfer += oprot->writeFieldBegin("string_val", ::apache::thrift::protocol::T_STRING, 8);
    xfer += oprot->writeString(this->string_val);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(PValue &a, PValue &b) {
  using ::std::swap;
  swap(a.bool_val, b.bool_val);
  swap(a.byte_val, b.byte_val);
  swap(a.short_val, b.short_val);
  swap(a.int_val, b.int_val);
  swap(a.long_val, b.long_val);
  swap(a.double_val, b.double_val);
  swap(a.binary_val, b.binary_val);
  swap(a.string_val, b.string_val);
  swap(a.__isset, b.__isset);
}

const char* Value::ascii_fingerprint = "4F3FDDF167445C014ED96B41C3F03818";
const uint8_t Value::binary_fingerprint[16] = {0x4F,0x3F,0xDD,0xF1,0x67,0x44,0x5C,0x01,0x4E,0xD9,0x6B,0x41,0xC3,0xF0,0x38,0x18};

uint32_t Value::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->p_val.read(iprot);
          this->__isset.p_val = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->list_value.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _etype7;
            xfer += iprot->readListBegin(_etype7, _size4);
            this->list_value.resize(_size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              xfer += this->list_value[_i8].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.list_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->map_value.clear();
            uint32_t _size9;
            ::apache::thrift::protocol::TType _ktype10;
            ::apache::thrift::protocol::TType _vtype11;
            xfer += iprot->readMapBegin(_ktype10, _vtype11, _size9);
            uint32_t _i13;
            for (_i13 = 0; _i13 < _size9; ++_i13)
            {
              PValue _key14;
              xfer += _key14.read(iprot);
              PValue& _val15 = this->map_value[_key14];
              xfer += _val15.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.map_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Value::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("Value");

  if (this->__isset.p_val) {
    xfer += oprot->writeFieldBegin("p_val", ::apache::thrift::protocol::T_STRUCT, 1);
    xfer += this->p_val.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.list_value) {
    xfer += oprot->writeFieldBegin("list_value", ::apache::thrift::protocol::T_LIST, 2);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->list_value.size()));
      std::vector<PValue> ::const_iterator _iter16;
      for (_iter16 = this->list_value.begin(); _iter16 != this->list_value.end(); ++_iter16)
      {
        xfer += (*_iter16).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.map_value) {
    xfer += oprot->writeFieldBegin("map_value", ::apache::thrift::protocol::T_MAP, 3);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRUCT, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->map_value.size()));
      std::map<PValue, PValue> ::const_iterator _iter17;
      for (_iter17 = this->map_value.begin(); _iter17 != this->map_value.end(); ++_iter17)
      {
        xfer += _iter17->first.write(oprot);
        xfer += _iter17->second.write(oprot);
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Value &a, Value &b) {
  using ::std::swap;
  swap(a.p_val, b.p_val);
  swap(a.list_value, b.list_value);
  swap(a.map_value, b.map_value);
  swap(a.__isset, b.__isset);
}

const char* RowSchema::ascii_fingerprint = "721FE21C727F9084A88D8C213CA0EE4B";
const uint8_t RowSchema::binary_fingerprint[16] = {0x72,0x1F,0xE2,0x1C,0x72,0x7F,0x90,0x84,0xA8,0x8D,0x8C,0x21,0x3C,0xA0,0xEE,0x4B};

uint32_t RowSchema::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_fields = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->fields.clear();
            uint32_t _size18;
            ::apache::thrift::protocol::TType _etype21;
            xfer += iprot->readListBegin(_etype21, _size18);
            this->fields.resize(_size18);
            uint32_t _i22;
            for (_i22 = 0; _i22 < _size18; ++_i22)
            {
              xfer += this->fields[_i22].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_fields = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_fields)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t RowSchema::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("RowSchema");

  xfer += oprot->writeFieldBegin("fields", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->fields.size()));
    std::vector<Field> ::const_iterator _iter23;
    for (_iter23 = this->fields.begin(); _iter23 != this->fields.end(); ++_iter23)
    {
      xfer += (*_iter23).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(RowSchema &a, RowSchema &b) {
  using ::std::swap;
  swap(a.fields, b.fields);
}

}}} // namespace
