/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef schema_CONSTANTS_H
#define schema_CONSTANTS_H

#include "schema_types.h"

namespace surfingdb { namespace meta { namespace schema {

class schemaConstants {
 public:
  schemaConstants();

};

extern const schemaConstants g_schema_constants;

}}} // namespace

#endif
