version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/drsquirrel-java-project"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/surfingthriftjni"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/examples/fake-cogroup-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

