/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mabs_CONSTANTS_H
#define mabs_CONSTANTS_H

#include "mabs_types.h"



class mabsConstants {
 public:
  mabsConstants();

};

extern const mabsConstants g_mabs_constants;



#endif
