/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mabs_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

void MabsMetrics::__set_timestamp(const int64_t val) {
  this->timestamp = val;
}

void MabsMetrics::__set_service_tags(const std::string& val) {
  this->service_tags = val;
__isset.service_tags = true;
}

void MabsMetrics::__set_node_tags(const std::string& val) {
  this->node_tags = val;
__isset.node_tags = true;
}

void MabsMetrics::__set_counters(const std::map<std::string, int64_t> & val) {
  this->counters = val;
__isset.counters = true;
}

void MabsMetrics::__set_gauges(const std::map<std::string, double> & val) {
  this->gauges = val;
__isset.gauges = true;
}

void MabsMetrics::__set_histograms(const std::map<std::string, std::string> & val) {
  this->histograms = val;
__isset.histograms = true;
}

void MabsMetrics::__set_service_name(const std::string& val) {
  this->service_name = val;
__isset.service_name = true;
}

void MabsMetrics::__set_double_counters(const std::map<std::string, double> & val) {
  this->double_counters = val;
__isset.double_counters = true;
}
std::ostream& operator<<(std::ostream& out, const MabsMetrics& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t MabsMetrics::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_timestamp = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->timestamp);
          isset_timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->service_tags);
          this->__isset.service_tags = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->node_tags);
          this->__isset.node_tags = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->counters.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _ktype1;
            ::apache::thrift::protocol::TType _vtype2;
            xfer += iprot->readMapBegin(_ktype1, _vtype2, _size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              std::string _key5;
              xfer += iprot->readString(_key5);
              int64_t& _val6 = this->counters[_key5];
              xfer += iprot->readI64(_val6);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.counters = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->gauges.clear();
            uint32_t _size7;
            ::apache::thrift::protocol::TType _ktype8;
            ::apache::thrift::protocol::TType _vtype9;
            xfer += iprot->readMapBegin(_ktype8, _vtype9, _size7);
            uint32_t _i11;
            for (_i11 = 0; _i11 < _size7; ++_i11)
            {
              std::string _key12;
              xfer += iprot->readString(_key12);
              double& _val13 = this->gauges[_key12];
              xfer += iprot->readDouble(_val13);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.gauges = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->histograms.clear();
            uint32_t _size14;
            ::apache::thrift::protocol::TType _ktype15;
            ::apache::thrift::protocol::TType _vtype16;
            xfer += iprot->readMapBegin(_ktype15, _vtype16, _size14);
            uint32_t _i18;
            for (_i18 = 0; _i18 < _size14; ++_i18)
            {
              std::string _key19;
              xfer += iprot->readString(_key19);
              std::string& _val20 = this->histograms[_key19];
              xfer += iprot->readString(_val20);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.histograms = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->service_name);
          this->__isset.service_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->double_counters.clear();
            uint32_t _size21;
            ::apache::thrift::protocol::TType _ktype22;
            ::apache::thrift::protocol::TType _vtype23;
            xfer += iprot->readMapBegin(_ktype22, _vtype23, _size21);
            uint32_t _i25;
            for (_i25 = 0; _i25 < _size21; ++_i25)
            {
              std::string _key26;
              xfer += iprot->readString(_key26);
              double& _val27 = this->double_counters[_key26];
              xfer += iprot->readDouble(_val27);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.double_counters = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_timestamp)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t MabsMetrics::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("MabsMetrics");

  xfer += oprot->writeFieldBegin("timestamp", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->timestamp);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.service_tags) {
    xfer += oprot->writeFieldBegin("service_tags", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeString(this->service_tags);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.node_tags) {
    xfer += oprot->writeFieldBegin("node_tags", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeString(this->node_tags);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.counters) {
    xfer += oprot->writeFieldBegin("counters", ::apache::thrift::protocol::T_MAP, 4);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->counters.size()));
      std::map<std::string, int64_t> ::const_iterator _iter28;
      for (_iter28 = this->counters.begin(); _iter28 != this->counters.end(); ++_iter28)
      {
        xfer += oprot->writeString(_iter28->first);
        xfer += oprot->writeI64(_iter28->second);
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.gauges) {
    xfer += oprot->writeFieldBegin("gauges", ::apache::thrift::protocol::T_MAP, 5);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_DOUBLE, static_cast<uint32_t>(this->gauges.size()));
      std::map<std::string, double> ::const_iterator _iter29;
      for (_iter29 = this->gauges.begin(); _iter29 != this->gauges.end(); ++_iter29)
      {
        xfer += oprot->writeString(_iter29->first);
        xfer += oprot->writeDouble(_iter29->second);
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.histograms) {
    xfer += oprot->writeFieldBegin("histograms", ::apache::thrift::protocol::T_MAP, 6);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->histograms.size()));
      std::map<std::string, std::string> ::const_iterator _iter30;
      for (_iter30 = this->histograms.begin(); _iter30 != this->histograms.end(); ++_iter30)
      {
        xfer += oprot->writeString(_iter30->first);
        xfer += oprot->writeString(_iter30->second);
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.service_name) {
    xfer += oprot->writeFieldBegin("service_name", ::apache::thrift::protocol::T_STRING, 7);
    xfer += oprot->writeString(this->service_name);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.double_counters) {
    xfer += oprot->writeFieldBegin("double_counters", ::apache::thrift::protocol::T_MAP, 8);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_DOUBLE, static_cast<uint32_t>(this->double_counters.size()));
      std::map<std::string, double> ::const_iterator _iter31;
      for (_iter31 = this->double_counters.begin(); _iter31 != this->double_counters.end(); ++_iter31)
      {
        xfer += oprot->writeString(_iter31->first);
        xfer += oprot->writeDouble(_iter31->second);
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(MabsMetrics &a, MabsMetrics &b) {
  using ::std::swap;
  swap(a.timestamp, b.timestamp);
  swap(a.service_tags, b.service_tags);
  swap(a.node_tags, b.node_tags);
  swap(a.counters, b.counters);
  swap(a.gauges, b.gauges);
  swap(a.histograms, b.histograms);
  swap(a.service_name, b.service_name);
  swap(a.double_counters, b.double_counters);
  swap(a.__isset, b.__isset);
}

MabsMetrics::MabsMetrics(const MabsMetrics& other32) {
  timestamp = other32.timestamp;
  service_tags = other32.service_tags;
  node_tags = other32.node_tags;
  counters = other32.counters;
  gauges = other32.gauges;
  histograms = other32.histograms;
  service_name = other32.service_name;
  double_counters = other32.double_counters;
  __isset = other32.__isset;
}
MabsMetrics& MabsMetrics::operator=(const MabsMetrics& other33) {
  timestamp = other33.timestamp;
  service_tags = other33.service_tags;
  node_tags = other33.node_tags;
  counters = other33.counters;
  gauges = other33.gauges;
  histograms = other33.histograms;
  service_name = other33.service_name;
  double_counters = other33.double_counters;
  __isset = other33.__isset;
  return *this;
}
void MabsMetrics::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "MabsMetrics(";
  out << "timestamp=" << to_string(timestamp);
  out << ", " << "service_tags="; (__isset.service_tags ? (out << to_string(service_tags)) : (out << "<null>"));
  out << ", " << "node_tags="; (__isset.node_tags ? (out << to_string(node_tags)) : (out << "<null>"));
  out << ", " << "counters="; (__isset.counters ? (out << to_string(counters)) : (out << "<null>"));
  out << ", " << "gauges="; (__isset.gauges ? (out << to_string(gauges)) : (out << "<null>"));
  out << ", " << "histograms="; (__isset.histograms ? (out << to_string(histograms)) : (out << "<null>"));
  out << ", " << "service_name="; (__isset.service_name ? (out << to_string(service_name)) : (out << "<null>"));
  out << ", " << "double_counters="; (__isset.double_counters ? (out << to_string(double_counters)) : (out << "<null>"));
  out << ")";
}


