/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mabs_TYPES_H
#define mabs_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class MabsMetrics;

typedef struct _MabsMetrics__isset {
  _MabsMetrics__isset() : service_tags(false), node_tags(false), counters(false), gauges(false), histograms(false), service_name(false), double_counters(false) {}
  bool service_tags :1;
  bool node_tags :1;
  bool counters :1;
  bool gauges :1;
  bool histograms :1;
  bool service_name :1;
  bool double_counters :1;
} _MabsMetrics__isset;

class MabsMetrics : public virtual ::apache::thrift::TBase {
 public:

  MabsMetrics(const MabsMetrics&);
  MabsMetrics& operator=(const MabsMetrics&);
  MabsMetrics() : timestamp(0), service_tags(), node_tags(), service_name() {
  }
  int64_t timestamp;
  std::string service_tags;
  std::string node_tags;
  std::map<std::string, int64_t>  counters;
  std::map<std::string, double>  gauges;
  std::map<std::string, std::string>  histograms;
  std::string service_name;
  std::map<std::string, double>  double_counters;

  _MabsMetrics__isset __isset;

  void __set_timestamp(const int64_t val);

  void __set_service_tags(const std::string& val);

  void __set_node_tags(const std::string& val);

  void __set_counters(const std::map<std::string, int64_t> & val);

  void __set_gauges(const std::map<std::string, double> & val);

  void __set_histograms(const std::map<std::string, std::string> & val);

  void __set_service_name(const std::string& val);

  void __set_double_counters(const std::map<std::string, double> & val);

  bool operator == (const MabsMetrics & rhs) const
  {
    if (!(timestamp == rhs.timestamp))
      return false;
    if (__isset.service_tags != rhs.__isset.service_tags)
      return false;
    else if (__isset.service_tags && !(service_tags == rhs.service_tags))
      return false;
    if (__isset.node_tags != rhs.__isset.node_tags)
      return false;
    else if (__isset.node_tags && !(node_tags == rhs.node_tags))
      return false;
    if (__isset.counters != rhs.__isset.counters)
      return false;
    else if (__isset.counters && !(counters == rhs.counters))
      return false;
    if (__isset.gauges != rhs.__isset.gauges)
      return false;
    else if (__isset.gauges && !(gauges == rhs.gauges))
      return false;
    if (__isset.histograms != rhs.__isset.histograms)
      return false;
    else if (__isset.histograms && !(histograms == rhs.histograms))
      return false;
    if (__isset.service_name != rhs.__isset.service_name)
      return false;
    else if (__isset.service_name && !(service_name == rhs.service_name))
      return false;
    if (__isset.double_counters != rhs.__isset.double_counters)
      return false;
    else if (__isset.double_counters && !(double_counters == rhs.double_counters))
      return false;
    return true;
  }
  bool operator != (const MabsMetrics &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MabsMetrics & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(MabsMetrics &a, MabsMetrics &b);

std::ostream& operator<<(std::ostream& out, const MabsMetrics& obj);



#endif
