// Targeted by JavaCPP version 1.5.8: DO NOT EDIT THIS FILE

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class CDataJavaToCppExample extends CDataJavaConfig {
    static { Loader.load(); }

// Parsed from /home/chen/surfing-db/src/CDataCppBridge.h

// #include <iostream>
// #include <arrow/api.h>
// #include <arrow/c/bridge.h>

public static native void FillInt64Array(@Cast("const uintptr_t") long c_schema_ptr, @Cast("const uintptr_t") long c_array_ptr);


}
